name: Release

on:
  push:
    branches:
      - prod

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install -g semantic-release@21.0.7 conventional-changelog-conventionalcommits@6.1.0 @semantic-release/commit-analyzer@10.0.1 @semantic-release/gitlab @semantic-release/changelog @semantic-release/release-notes-generator@11.0.4

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
